---
- name: Create Nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ project_name }}.conf

- name: Enable site
  file:
    src: "/etc/nginx/sites-available/{{ project_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ project_name }}.conf"
    state: link
    force: yes

- name: Test Nginx
  command: nginx -t
  notify: Reload Nginx
