---
galaxy_info:
  author: Mina Amin
  description: Install and configure Laravel application with Nginx, PHP, and MariaDB.
  company: ""
  
  license: "MIT"

  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - laravel
    - nginx
    - mariadb
    - php
    - webserver
    - database
    - deployment
    - ansible
    - devops
    - automation
    - minaamin
    - mina amin